Repository wpmudev/shared-ui-react, pull requests merged in 2021-04, with the labels that each got.

#76 ✨ new(react-box): Tag props for title.
  packages/react-box/docs/box.stories.js
  packages/react-box/lib/box.js
Labels: improvement

#72 📝 docs(react-button): Display the button as a label, anchor, and button
  packages/react-button/docs/button.stories.js
Labels: documentation

#73 🐛 fix(react-button): Remove forwardRef and fix `undefined` in classes.
  packages/react-button/docs/button.stories.js
  packages/react-button/lib/button.js
Labels: bug, improvement

#74 🐛 fix(react-input): Give more flexibility to the 'input' component.
  packages/react-input/docs/react-input.stories.js
  packages/react-input/lib/react-input.js
Labels: improvement

#80 ✨ new(react-box): Make footer more flexible.
  packages/react-box/docs/box-footer.stories.js
  packages/react-box/lib/box.js
Labels: new

#83 ✨ new(react-box): Make `body` more flexible with props.
  packages/react-box/docs/box-body.stories.js
  packages/react-box/lib/box.js
Labels: new

#79 📝 docs(react-button): Fix not working controls and add more properties.
  packages/react-button/docs/button.stories.js
Labels: documentation

#84 🐛 fix(react-box): Reestructure `header` props.
  packages/react-box/docs/box-header.stories.js
  packages/react-box/lib/box.js
Labels: bug

#85 ⬆️ Upgrade dependencies.
  package.json
  packages/compiler/package.json
  packages/react-accordion/package.json
  packages/react-box/package.json
  packages/react-button-icon/package.json
  packages/react-input/package.json
  packages/react-notifications/package.json
  packages/react-post/package.json
  yarn.lock
Labels: improvement

#87 🐛 fix(react-dropdown): Prevent clicks from propagating.
  packages/react-dropdown/lib/react-dropdown.js
Labels: improvement

#88 🐛 fix(react-dropdown): Clicking on its options closes the menu.
  packages/react-dropdown/lib/react-dropdown.js
Labels: bug

#89 🐛 fix(react-dropdown): Menu not closing after clicking on an option.
  packages/react-dropdown/lib/react-dropdown.js
Labels: bug

#86 🐛 fix(react-input): Remove extra space when passing the 'Input' props.
  packages/react-input/lib/react-input.js
Labels: bug

#91 New/modal replace
  packages/react-modal/docs/modal.stories.js
  packages/react-modal/lib/modal.js
Labels: new

#95 ✨ new/react-button-icon: Icon size property.
  packages/react-button-icon/lib/react-button-icon.js
Labels: new

#94 🐛 fix/react-button-icon: Remove `forwardRef`.
  packages/react-button-icon/lib/react-button-icon.js
Labels: bug

#96 🐛 fix/react-button-icon: Adjust the `render` return.
  packages/react-button-icon/lib/react-button-icon.js
Labels: improvement

#93 🐛 fix/react-button-icon: Prevent `undefined` class from being added.
  packages/react-button-icon/lib/react-button-icon.js
Labels: bug

#90 🐛 fix(react-dropdown): Stop click propagation from the dropdown component.
  packages/react-dropdown/lib/react-dropdown.js
Labels: bug

#92 ✨ new(react-modal): Create new component.
  packages/core/lib/core.js
  packages/react-modal/LICENSE
  packages/react-modal/README.md
  packages/react-modal/__tests__/react-modal.test.js
  packages/react-modal/dist/react-modal.cjs.js
  packages/react-modal/dist/react-modal.esm.js
  packages/react-modal/docs/assets/beehive-welcome.png
  packages/react-modal/docs/assets/hustle-footer.png
  packages/react-modal/docs/assets/hustle-footer@2x.png
  packages/react-modal/docs/react-modal.stories.js
  packages/react-modal/lib/react-modal.js
  packages/react-modal/package-lock.json
  packages/react-modal/package.json
  yarn.lock
Labels: new

#98 🐛 fix/react-modal: Remove conditional rendering when using the inner modal's state.
  packages/react-modal/lib/react-modal.js
Labels: improvement

#97 🐛 fix/react-button: Console error when the button is `loading`.
  packages/react-button/lib/button.js
Labels: bug

#99 ✨ new(react-dropdown): Allow options to change font color.
  packages/react-dropdown/docs/react-dropdown.stories.js
  packages/react-dropdown/lib/react-dropdown.js
  packages/react-dropdown/package.json
Labels: new

#100 🐛 fix(browserslist): Update browsers data.
  yarn.lock
Labels: improvement

#101 🐛 fix(react-modal): React doesn’t recognize prop on DOM element.
  packages/compiler/lib/builder.js
  packages/compiler/package.json
  yarn.lock
Labels: bug

#109 🐛 fix(react-dropdown): Uncolored menu option icon.
  packages/react-dropdown/lib/react-dropdown.js
Labels: bug

#110 🐛.fix(react-modal): Unnecessary extra margins from `sui-wrapper` class.
  .storybook/preview.js
  package.json
  packages/react-modal/docs/react-modal.stories.js
  packages/react-modal/package.json
  yarn.lock
Labels: bug
