Repository wpmudev/shared-ui-react, pull requests merged in 2021-06, with the labels that each got.

#123 🐛 fix(react-post): Decode post title.
  packages/react-post/lib/react-post.js
Labels: bug

#121 ✨ new(react-pagination): Create package.
  packages/react-pagination/LICENSE
  packages/react-pagination/README.md
  packages/react-pagination/__tests__/react-pagination.test.js
  packages/react-pagination/docs/react-pagination.stories.js
  packages/react-pagination/lib/react-pagination.js
  packages/react-pagination/package.json
Labels: new

#124 🐛 fix(react-accordion): Use hooks instead of classes.
  packages/react-accordion/lib/react-accordion.js
Labels: improvement

#125 🐛 fix(react-accordion): Allow columns on item header.
  packages/react-accordion/lib/react-accordion.js
Labels: improvement

#126 🐛 fix(react-accordion): Component properties are rendered on markup.
  packages/react-accordion/lib/react-accordion.js
Labels: bug

#127 ✨ new(react-pagination): Add package to core.
  packages/core/lib/core.js
  packages/core/package.json
Labels: core, new

#128 🐛 fix(core): Set `styled-components` dependency to latest/same version for all packages.
  packages/react-accordion/package.json
  packages/react-box/package.json
  packages/react-dropdown/package.json
  packages/react-post/package.json
  yarn.lock
Labels: core

#122 ✨ new(react-pagination): Split component in navigation and results.
  packages/react-pagination/README.md
  packages/react-pagination/docs/react-pagination.stories.js
  packages/react-pagination/lib/react-pagination.js
  packages/react-pagination/package.json
Labels: new
