Repository wpmudev/shared-ui-react, pull requests merged in 2022-04, with the labels that each got.

#171 Set `react` dependency to latest version for all packages.
  package.json
  packages/react-accordion/package.json
  packages/react-box/package.json
  packages/react-button-icon/package.json
  packages/react-button/package.json
  packages/react-dropdown/package.json
  packages/react-input/package.json
  packages/react-modal/package.json
  packages/react-notifications/package.json
  packages/react-pagination/package.json
  packages/react-post/package.json
  packages/react-progress-bar/package.json
  yarn.lock
Labels: internal

#172 docs(button): Improve stories.
  packages/react-button/docs/button-demo.stories.js
  packages/react-button/docs/button-modifiers.stories.js
  packages/react-button/docs/button-states.stories.js
Labels: documentation

#173 docs(button-icon): Improve stories.
  packages/react-button-icon/docs/react-button-icon-demo.stories.js
  packages/react-button-icon/docs/react-button-icon-modifiers.stories.js
  packages/react-button-icon/docs/react-button-icon-states.stories.js
  packages/react-button-icon/docs/react-button-icon.stories.js
Labels: documentation

#177 docs(dropdown): Improve stories.
  packages/react-dropdown/docs/react-dropdown-demo.stories.js
  packages/react-dropdown/docs/react-dropdown-modifiers.stories.js
  packages/react-dropdown/docs/react-dropdown-states.stories.js
  packages/react-dropdown/docs/react-dropdown.stories.js
Labels: documentation

#178 docs(post): Improve stories.
  packages/react-post/docs/images/demo.png
  packages/react-post/docs/react-post-demo.stories.js
  packages/react-post/docs/react-post-modifiers.stories.js
  packages/react-post/docs/react-post-states.stories.js
  packages/react-post/docs/react-post.stories.js
Labels: documentation

#179 docs(notifications): Improve stories.
  packages/react-notifications/docs/react-notifications-demo.stories.js
  packages/react-notifications/docs/react-notifications-modifiers.stories.js
  packages/react-notifications/docs/react-notifications-multi.stories.js
  packages/react-notifications/docs/react-notifications-single.stories.js
  packages/react-notifications/docs/react-notifications-states.stories.js
Labels: documentation

#180 fix(notifications): Loading must be a state of the component.
  packages/react-notifications/docs/react-notifications-demo.stories.js
  packages/react-notifications/docs/react-notifications-states.stories.js
  packages/react-notifications/lib/react-notifications.js
Labels: improvement

#181 fix(notifications): Ability to edit dismiss button label.
  packages/react-notifications/docs/react-notifications-demo.stories.js
  packages/react-notifications/lib/react-notifications.js
Labels: improvement

#182 fix(core): Missing `ProgressBar` component.
  packages/core/lib/core.js
Labels: bug

#174 fix(accordions): Demo image is missing in the stories.
  packages/react-accordion/docs/assets/images/logo.png
  packages/react-accordion/docs/react-accordion.stories.js
Labels: bug

#185 bug(post): Disabled state is missing.
  packages/react-post/lib/react-post.js
Labels: bug

#184 fix(dropdown): Add `disabled` property for trigger menu button.
  packages/react-dropdown/lib/react-dropdown.js
Labels: improvement

#186 fix(dropdown): Missing `disabled` styles for options.
  packages/react-dropdown/lib/react-dropdown.js
Labels: bug

#190 fix(core): Wrong package version for `builder`.
  packages/core/package.json
Labels: bug

#192 fix(box): Wrong package version for `builder`.
  packages/react-box/package.json
Labels: bug

#193 fix(button): Wrong package version for `builder`.
  packages/react-button/package.json
Labels: bug

#194 fix(dropdown): Wrong package version for `builder`.
  packages/react-dropdown/package.json
Labels: bug

#195 fix(input): Wrong package version for `builder`.
  packages/react-input/package.json
Labels: bug

#196 fix(modal): Wrong package version for `builder`.
  packages/react-modal/package.json
Labels: bug

#197 fix(notifications): Wrong package version for `builder`.
  packages/react-notifications/package.json
Labels: bug

#198 fix(pagination): Wrong package version for `builder`.
  packages/react-pagination/package.json
Labels: bug

#199 fix(post): Wrong package version for `builder`.
  packages/react-post/package.json
Labels: bug

#200 fix(progress-bar): Wrong package version for `builder`.
  packages/react-progress-bar/package.json
Labels: bug

#187 new(notifications): Support callback function for dismiss button.
  packages/react-notifications/docs/react-notifications-demo.stories.js
  packages/react-notifications/docs/react-notifications-modifiers.stories.js
  packages/react-notifications/lib/react-notifications.js
Labels: new

#175 docs(input): Improve stories.
  packages/react-input/docs/input-demo.stories.js
  packages/react-input/docs/input-modifiers-field.stories.js
  packages/react-input/docs/input-states.stories.js
  packages/react-input/docs/react-input.stories.js
Labels: documentation

#207 new(input): Add `prefix` prop.
  packages/react-input/docs/input-demo.stories.js
  packages/react-input/docs/input-modifiers-field.stories.js
  packages/react-input/lib/react-input.js
Labels: documentation, new

#176 docs(progress-bar): Improve stories.
  packages/react-progress-bar/docs/progress-bar-demo.stories.js
  packages/react-progress-bar/docs/progress-bar-elements.stories.js
  packages/react-progress-bar/docs/progress-bar-modifiers.stories.js
  packages/react-progress-bar/docs/progress-bar-states.stories.js
  packages/react-progress-bar/docs/react-progress-bar.stories.js
Labels: documentation

#208 docs(accordion): Improve stories.
  packages/react-accordion/docs/react-accordion-demo.stories.js
  packages/react-accordion/docs/react-accordion-elements.stories.js
  packages/react-accordion/docs/react-accordion-item.stories.js
  packages/react-accordion/docs/react-accordion.stories.js
Labels: documentation

#183 fix(post): Image keeps on loading when is empty or null.
  packages/react-post/lib/react-post.js
Labels: bug

#206 new(input): Add `suffix` prop.
  packages/react-input/docs/input-demo.stories.js
  packages/react-input/docs/input-modifiers-field.stories.js
  packages/react-input/lib/react-input.js
Labels: new

#204 fix: Invalid hook call.
  package.json
  packages/react-accordion/package.json
  packages/react-box/package.json
  packages/react-button-icon/package.json
  packages/react-button/package.json
  packages/react-dropdown/package.json
  packages/react-input/package.json
  packages/react-modal/package.json
  packages/react-notifications/package.json
  packages/react-pagination/package.json
  packages/react-post/package.json
  packages/react-progress-bar/package.json
  yarn.lock
Labels: internal
