Repository wpmudev/shared-ui-react, pull requests merged in 2022-05, with the labels that each got.

#209 fix(pagination): Parent wrapper breaks the component.
  packages/react-pagination/lib/react-pagination.js
Labels: bug

#213 docs(pagination): Improve stories.
  packages/react-pagination/docs/react-pagination-demo.stories.js
  packages/react-pagination/docs/react-pagination-elements.stories.js
  packages/react-pagination/docs/react-pagination-template.stories.js
  packages/react-pagination/docs/react-pagination.stories.js
Labels: documentation

#217 Configure CodeQL alerts.
  .github/workflows/codeql-analysis.yml
Labels: internal

#226 Run Chromatic when pushing to any release branch.
  .github/workflows/chromatic.yml
Labels: internal

#227 fix(input): Class identifier is wrong.
  packages/react-input/lib/react-input.js
Labels: bug

#228 fix(pagination): Repeated property.
  packages/react-pagination/lib/react-pagination.js
Labels: bug

#231 fix(progress-bar): Using isNaN may lead to unexpected results.
  packages/react-progress-bar/lib/react-progress-bar.js
Labels: improvement

#229 fix(dropdown): Case clause is duplicated.
  packages/react-dropdown/lib/react-dropdown.js
Labels: improvement

#241 Incorrect comparison in axios.
  package.json
  yarn.lock
Labels: bug, dependencies

#246 Regular Expression Denial of Service in trim-newlines.
  package.json
  yarn.lock
Labels: bug, dependencies

#255 fix(dropdown): Using component state to compute could lead to undesired behavior.
  packages/react-dropdown/lib/react-dropdown.js
Labels: improvement

#242 fix(internal): Deprecated `disabled` parameter in stories.
  packages/react-accordion/docs/react-accordion-demo.stories.js
  packages/react-accordion/docs/react-accordion-elements.stories.js
  packages/react-button-icon/docs/react-button-icon-demo.stories.js
  packages/react-button-icon/docs/react-button-icon-modifiers.stories.js
  packages/react-button-icon/docs/react-button-icon-states.stories.js
  packages/react-button/docs/button-demo.stories.js
  packages/react-button/docs/button-modifiers.stories.js
  packages/react-button/docs/button-states.stories.js
  packages/react-dropdown/docs/react-dropdown-demo.stories.js
  packages/react-dropdown/docs/react-dropdown-modifiers.stories.js
  packages/react-dropdown/docs/react-dropdown-states.stories.js
  packages/react-input/docs/input-demo.stories.js
  packages/react-input/docs/input-modifiers-field.stories.js
  packages/react-input/docs/input-modifiers-input.stories.js
  packages/react-input/docs/input-states.stories.js
  packages/react-notifications/docs/react-notifications-modifiers.stories.js
  packages/react-notifications/docs/react-notifications-states.stories.js
  packages/react-pagination/docs/react-pagination-demo.stories.js
  packages/react-pagination/docs/react-pagination-elements.stories.js
  packages/react-pagination/docs/react-pagination-template.stories.js
  packages/react-post/docs/react-post-demo.stories.js
  packages/react-post/docs/react-post-modifiers.stories.js
  packages/react-post/docs/react-post-states.stories.js
  packages/react-progress-bar/docs/progress-bar-demo.stories.js
  packages/react-progress-bar/docs/progress-bar-elements.stories.js
  packages/react-progress-bar/docs/progress-bar-modifiers.stories.js
  packages/react-progress-bar/docs/progress-bar-states.stories.js
Labels: documentation

#259 fix(internal): Upgrade to Storybook 6.4.22.
  .storybook/main.js
  .storybook/preview.js
  package.json
  packages/react-accordion/docs/react-accordion-demo.stories.js
  packages/react-accordion/docs/react-accordion-elements.stories.js
  packages/react-button-icon/docs/react-button-icon-demo.stories.js
  packages/react-button-icon/docs/react-button-icon-modifiers.stories.js
  packages/react-button-icon/docs/react-button-icon-states.stories.js
  packages/react-button/docs/button-demo.stories.js
  packages/react-button/docs/button-modifiers.stories.js
  packages/react-button/docs/button-states.stories.js
  packages/react-dropdown/docs/react-dropdown-demo.stories.js
  packages/react-dropdown/docs/react-dropdown-modifiers.stories.js
  packages/react-dropdown/docs/react-dropdown-states.stories.js
  packages/react-input/docs/input-demo.stories.js
  packages/react-input/docs/input-modifiers-field.stories.js
  packages/react-input/docs/input-modifiers-input.stories.js
  packages/react-input/docs/input-states.stories.js
  packages/react-notifications/docs/react-notifications-modifiers.stories.js
  packages/react-notifications/docs/react-notifications-states.stories.js
  packages/react-pagination/docs/react-pagination-demo.stories.js
  packages/react-pagination/docs/react-pagination-elements.stories.js
  packages/react-pagination/docs/react-pagination-template.stories.js
  packages/react-post/docs/react-post-demo.stories.js
  packages/react-post/docs/react-post-modifiers.stories.js
  packages/react-post/docs/react-post-states.stories.js
  packages/react-progress-bar/docs/progress-bar-demo.stories.js
  packages/react-progress-bar/docs/progress-bar-elements.stories.js
  packages/react-progress-bar/docs/progress-bar-modifiers.stories.js
  packages/react-progress-bar/docs/progress-bar-states.stories.js
  yarn.lock
Labels: internal

#234 build(deps): Cross-site Scripting in Prism.
  yarn.lock
Labels: internal, dependencies

#260 Remove `notes` support on add-ons panel.
  .storybook/main.js
  package.json
  packages/react-accordion/docs/react-accordion-demo.stories.js
  packages/react-accordion/docs/react-accordion-elements.stories.js
  packages/react-box/docs/box-body.stories.js
  packages/react-box/docs/box-footer.stories.js
  packages/react-box/docs/box-header.stories.js
  packages/react-box/docs/box-section.stories.js
  packages/react-box/docs/box.stories.js
  packages/react-button-icon/docs/react-button-icon-demo.stories.js
  packages/react-button-icon/docs/react-button-icon-modifiers.stories.js
  packages/react-button-icon/docs/react-button-icon-states.stories.js
  packages/react-button/docs/button-demo.stories.js
  packages/react-button/docs/button-modifiers.stories.js
  packages/react-button/docs/button-states.stories.js
  packages/react-dropdown/docs/react-dropdown-demo.stories.js
  packages/react-dropdown/docs/react-dropdown-modifiers.stories.js
  packages/react-dropdown/docs/react-dropdown-states.stories.js
  packages/react-input/docs/input-demo.stories.js
  packages/react-input/docs/input-modifiers-field.stories.js
  packages/react-input/docs/input-modifiers-input.stories.js
  packages/react-input/docs/input-states.stories.js
  packages/react-modal/docs/react-modal-replace.stories.js
  packages/react-modal/docs/react-modal-slider.stories.js
  packages/react-notifications/docs/react-notifications-demo.stories.js
  packages/react-notifications/docs/react-notifications-modifiers.stories.js
  packages/react-notifications/docs/react-notifications-states.stories.js
  packages/react-pagination/docs/react-pagination-demo.stories.js
  packages/react-pagination/docs/react-pagination-elements.stories.js
  packages/react-pagination/docs/react-pagination-template.stories.js
  packages/react-post/docs/react-post-demo.stories.js
  packages/react-post/docs/react-post-modifiers.stories.js
  packages/react-post/docs/react-post-states.stories.js
  packages/react-progress-bar/docs/progress-bar-demo.stories.js
  packages/react-progress-bar/docs/progress-bar-elements.stories.js
  packages/react-progress-bar/docs/progress-bar-modifiers.stories.js
  packages/react-progress-bar/docs/progress-bar-states.stories.js
  yarn.lock
Labels: internal

#261 build(deps): Inefficient Regular Expression Complexity in nth-check.
  package.json
  yarn.lock
Labels: internal, dependencies

#262 Regular expression denial of service in glob-parent.
  package.json
  yarn.lock
Labels: internal, dependencies

#230 fix(modal): Missing cleanup of timer in componentDidMount.
  packages/react-modal/lib/components/react-aria-modal.js
Labels: improvement

#232 fix(progress-bar): Comparing a string and a number with strict operator is pointless.
  packages/react-progress-bar/lib/react-progress-bar.js
Labels: improvement
