Repository wpmudev/shared-ui-react, pull requests merged in 2022-01, with the labels that each got.

#129 🐛 fix(react-modal): Trap focus without external library.
  packages/react-modal/README.md
  packages/react-modal/docs/images/beehive-welcome.png
  packages/react-modal/docs/images/hustle-footer.png
  packages/react-modal/docs/images/hustle-footer@2x.png
  packages/react-modal/docs/notes/docs-replace-one.md
  packages/react-modal/docs/notes/docs-replace-two.md
  packages/react-modal/docs/notes/docs-slider-one.md
  packages/react-modal/docs/notes/docs-slider-two.md
  packages/react-modal/docs/react-modal-default.stories.js
  packages/react-modal/docs/react-modal-replace.stories.js
  packages/react-modal/docs/react-modal-slider.stories.js
  packages/react-modal/docs/react-modal.stories.js
  packages/react-modal/lib/components/focus-trap-react.js
  packages/react-modal/lib/components/focus-trap.js
  packages/react-modal/lib/components/no-scroll.js
  packages/react-modal/lib/components/react-aria-modal.js
  packages/react-modal/lib/components/react-displace.js
  packages/react-modal/lib/components/tabbable.js
  packages/react-modal/lib/react-modal.js
  packages/react-modal/package.json
  yarn.lock
Labels: improvement

#147 🐛 fix(react-post): Misaligned description when `reading time` is missing.
  packages/react-post/lib/react-post.js
Labels: bug

#157 Update change log file to new structure.
  CHANGELOG.md
  CHANGELOG_ARCHIVE.md
Labels: internal
